version: "3.6"

services:
  db:
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DevDbPassword123

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=devCertPassw0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/servicequotes.pfx
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ./https:/https/:ro
    networks:
      - localdev
