version: "3.6"

volumes:
  quotesdata:

networks:
  localdev:
    name: localdev

services:
  db:
    image: postgres:13
    container_name: postgresql
    restart: unless-stopped
    volumes:
      - quotesdata:/var/lib/postgresql/data
    networks:
      - localdev

  api:
    build:
      context: .
      dockerfile: src/ServiceQuotes.Api/Dockerfile
    image: service-quotes/api:local
    container_name: webapi
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - localdev

  pgbackups:
    container_name: Backup
    image: prodrigestivill/postgres-backup-local
    restart: unless-stopped
    volumes:
      - ./backup:/backups
    depends_on:
      - db
    networks:
      - localdev
