version: "3.6"

services:
  db:
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sq_db
      - POSTGRES_USER=service_quotes
      - POSTGRES_PASSWORD=DevDbPassword123

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=devCertPassw0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/servicequotes.pfx
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ./https:/https/:ro
    networks:
      - localdev

  pgbackups:
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=sq_db
      - POSTGRES_USER=service_quotes
      - POSTGRES_PASSWORD=DevDbPassword123
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=81
